sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '6'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: HizBdevylmgI43/92y9+RDj5ScQBxLlLnOE/OPtHWXx4W375BH+oY1YN7kNGocSRMTughIpfUEh9yRvLts6QrEGggdsHhWadpnQiyxDC13/cLGgLsAekCNn7Cem4phAu1akSnEI9j6jmoQSWamE1RIOsq6AzR0zXrPTiVmwTh+xk9AR0oKhbt70GKFqPg1rFRDdKSH6XJ9C6XzOHoj31IetTpGgCGG1pY4VXDfmZf85ecDsv0jsq1KDIxU7y0R0Lv9GhXpFU31BMl8uk42SPEijDmjE4OXkbqJ5cGc4ZmLXyal2pxgHxURX6KQwzw6m3Qx3DkvhBbyOPsElXlw5hAYurPafHflXQLfY60UqI+GUau9BtNmgfHy0Vg05xyny5sBxQpz6JAIn/sarY3ejASFe/ni1yT+S+V92prOm/2X39WYmMAJnhiYl/WpV2yFkw4Nfga149C/Ln2HoWzFAa424AHOuaOeyL8t1Hg0HrsNJiXZbgfAB7NRlHdjJ2CHeOrW2cHVMU4odcVdvkCxp5d8MnZccLVEvjiQi0/iXc0nLb5hqMjZL5dPukW3fPRxU4FJU86QdO085fREOPHt/lSFyYI7ZTPVvwhCp47W/xWWPCsldHz3Mj+M1YirKy8bBNSyLGTuzHXE0jo0ohWRx1KljZgvfg9gHE5uoqjEwODD4=
  - secure: JQLz5nAzj+dtA+wdlUM74AnQHCxqzV4dQTmVv/9YnfVIfD6iV3yFYgE/98u7y5w3Bw14Ou0aU6XmqsKBaNyzZapftYSu7DGSrHtIWlzCJM1iqwtLedwE0cq4yEi17cv6F7SXdRpDao/SQsGkU4U+1jXMDnEnvkIGrDZhfRxGApCeV7sF7WMwSk1SHpylQx2Byl/Lbw0NQTfMl1KLOfrSw5gH6GLQq7LXZhD9lemlL9C1olxAnoTUfw2pY5vkotVc/cTUrqt9pS5XYD9ghEVRkYfG3VjAkpIzjnlFP4jpK0ZfhtT1HyYMngH5X6dtzMQWMjDXO+PKnqwNr5EVG2iXO9afSFdp4K2NcKuUNhsYNHO0hCPT4PmVwW+zmu3IvJ2t+GZbAaFyv50rfKsahOiqnZJGsmRJT9KZ6c2spARFC09TFDM0L/fZkf3Kjaa9sG66Ddxr+sIoQGEYQW9+g7dL3dUWaUlVmSJPGbXGXlQ86oEb5Hm5hRzga8RtNeI9mjU2+LfhRZEz9xd91avDhFYWjDKRSBf22UEkOu8/dDKYvKQ0y1qek/54TQ6hpj1w+66YGsORNNXQ+mUT6tlxKsDTTUN8VzMWoqKwnR8FyIdQLDikX59u7YK9cY0x965mrgBCDRQbZzclSblY9iCd22dUoNmcmZuzfpCluuTtqNkEU5U=
